### ISSUE TITLE
Except block in incubator.rest catches all exceptions

### ISSUE THREAD

**Issue by ryandub** [checkmate/simpl#88]
https://github.com/checkmate/simpl/blob/master/simpl/incubator/rest.py#L189-L190

This generic exception swallows any exceptions I raise in my wrapped route:

```
import myexchandler as exc

@bottle.post('/myroute')
@rest.schema(body_schema=MYSCHEMA, body_required=True,
                        default_body={})
def some_route(body, query):
  raise exc.HTTPError(body="I'M A TEAPOT!", status=418)
```

I would expect this to raise a 418 error. However, it will always raise a 400 because the error raised here is caught by the `except` in the wrapper and then a `bottle.abort(400...)` is called.

Is this `try`/`except` block needed? Can it be taken out or narrowed down?

**Comment by ryandub** [comment]
Meant to ping @larsbutler as I think you probably have the most perspective on what was going on there.

**Comment by ryandub** [comment]
@larsbutler @samstav @ziadsawalha  - I think there is a use case for the incubator validation code in some of the work @Pablosan is doing, but this issue could stand in the way. Any thoughts on a solution? In order to get this working the way I would expect it to, I just removed the whole try/except block (https://github.com/ryandub/simpl/commit/5bce9d8bacdc2146854f828e28a62c74e94ecf85), but I think that has its own implications.

Is there an ideal solution here?

**Comment by samstav** [comment]
@larsbutler @ryandub @ziadsawalha 

I think we should just change the

```python
except Exception as exc:
```

to

```python
except MultiValidationError as exc:
```

**Comment by ryandub** [comment]
@samstav What if it isn't valid JSON? Should https://github.com/checkmate/simpl/blob/master/simpl/incubator/rest.py#L160 be wrapped as well?

**Comment by samstav** [comment]
@ryandub good question.... Would that raise a ValueError ?

**Comment by Pablosan** [comment]
@samstav @ryandub I think we could solve this in the `incubator` code by following the approach here: https://github.com/checkmate/simpl/blob/master/simpl/rest.py#L39

Specifically, this moves the catch-all so that it only catches on a single line (the line that validates against the schema)

However, I am pretty sure that a call to `bottle.request.json` can result in an exception, so we should probably address that in both locations (`rest.body` and `incubator.rest.schema`).

Finally, why is this `schema` function only in `incubator`? It seems awfully close to what is already in `simpl.rest.body`, and we could get both in sync if we moved `schema` into `simpl.rest` and created a helper function that both of these functions (`body` and `schema`) could use.

**Comment by Pablosan** [comment]
Actually, it should be two helper functions: one that validates a JSON payload, and one that validates Query Params. Then they could be used independently if desired. For instance, `body` probably shouldn't have Query Param validation.

**Comment by samstav** [comment]
> I am pretty sure that a call to bottle.request.json can result in an exception

Correct, it can.

I agree that these helper(s) must be consolidated. I can appreciate both approaches, that is, having one decorator called `schema`, or two, one called `body()` and one called `query()`. Actually, my suggestion would be that we have all three, and the developer can choose which they want to use, where `schema` would just delegate out to the logic behind `body()` and `query()`.

Also, if `schema` sticks around, its implementation should change. The keyword arguments that are not supplied to the decorator should not be forwarded to the decorated function. For example, iff `body=` is supplied to  the decorator then only the `body` kwarg should be passed to the decorated function. In other words, the signature of the decorated function should only need to change for the arguments it actually uses instead of [hard-coding the line that passes `query` *and* `body` to the decorated function](https://github.com/checkmate/simpl/blob/v0.8.1/simpl/incubator/rest.py#L183-L188). The logic in the decorator should be smart enough to detect this.

**Comment by samstav** [comment]
And lastly we should always keep the try/except blocks as small as possible and the exceptions caught as specific as possible.
